# Analysis of Active Sellers Performance using Pandas

This project analyzes the performance of active sellers using a dataset.

The dataset includes seller details such as:
- Number of products listed
- Total units sold
- Ratings and reviews
- Pricing and discount information

**Steps Performed**
1. Data Loading
2. Data Cleaning (handling missing values and duplicates)
3. Feature Engineering (creating new columns)
4. Data Analysis (sorting, filtering, grouping)
5. Identifying successful sellers

**Key Insights**
- Sellers with higher ratings tend to have higher sales
- Discounts influence product sales significantly
- Sellers with more listed products generally sell more units
- Pricing strategy plays a key role in performance

This analysis helps understand the factors affecting seller success such as pricing, ratings, and product volume.

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving computed_insight_success_of_active_sellers.csv to computed_insight_success_of_active_sellers (1).csv

In [ ]:
import pandas as pd

df = pd.read_csv('computed_insight_success_of_active_sellers.csv')
df.head()

,merchantid,listedproducts,totalunitssold,meanunitssoldperproduct,rating,merchantratingscount,meanproductprices,meanretailprices,averagediscount,meandiscount,meanproductratingscount,totalurgencycount,urgencytextrate
0,5357bcf2bb72c5504882e889,2,120000,60000.0,4.219,320031.0,9.00,20.0,54.0,54.0,8836.0,1.0,50.0
1,5708773c3c02161b3f8c7900,5,107100,21420.0,3.934,139223.0,7.76,34.2,61.0,61.0,4010.0,3.0,60.0
2,5417aada4ad3ab27e954b76c,2,100007,50004.0,4.053,108048.0,8.00,8.0,-1.0,-1.0,5531.0,NaN,NaN
3,570f3a713a698c14278bb51e,1,100000,100000.0,3.889,19248.0,5.67,19.0,71.0,71.0,18393.0,1.0,100.0
4,53082ea15aefb07dfe1f2a4f,1,100000,100000.0,4.036,366898.0,5.00,33.0,85.0,85.0,13789.0,NaN,NaN

In [ ]:
import pandas as pd

df = pd.read_csv('computed_insight_success_of_active_sellers.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   merchantid               958 non-null    object
 1   listedproducts           958 non-null    int64
 2   totalunitssold           958 non-null    int64
 3   meanunitssoldperproduct  958 non-null    float64
 4   rating                   958 non-null    float64
 5   merchantratingscount     958 non-null    float64
 6   meanproductprices        958 non-null    float64
 7   meanretailprices         958 non-null    float64
 8   averagediscount          958 non-null    float64
 9   meandiscount             958 non-null    float64
 10  meanproductratingscount  958 non-null    float64
 11  totalurgencycount        391 non-null    float64
 12  urgencytextrate          391 non-null    float64
dtypes: float64(10), int64(2), object(1)
memory usage: 97.4+ KB

In [ ]:
import pandas as pd

df = pd.read_csv('computed_insight_success_of_active_sellers.csv')
df.tail()

,merchantid,listedproducts,totalunitssold,meanunitssoldperproduct,rating,merchantratingscount,meanproductprices,meanretailprices,averagediscount,meandiscount,meanproductratingscount,totalurgencycount,urgencytextrate
953,567bad8582c35f28103e5813,1,2,2.0,3.999,21307.0,11.00,10.0,-10.0,-10.0,1.0,NaN,NaN
954,5b24edf0d1c360301099e9c6,1,2,2.0,4.303,693.0,16.00,16.0,0.0,0.0,0.0,NaN,NaN
955,5d417e7070327a2743021677,1,1,1.0,3.598,378.0,2.72,9.0,70.0,70.0,0.0,NaN,NaN
956,5add589edb5f1f32114d07df,1,1,1.0,3.956,1134.0,14.00,14.0,0.0,0.0,0.0,NaN,NaN
957,5d4b8931933fb13f8a1fe232,1,1,1.0,4.007,1380.0,11.00,30.0,64.0,64.0,0.0,NaN,NaN

In [ ]:
import pandas as pd

df = pd.read_csv('computed_insight_success_of_active_sellers.csv')
df.describe()

,listedproducts,totalunitssold,meanunitssoldperproduct,rating,merchantratingscount,meanproductprices,meanretailprices,averagediscount,meandiscount,meanproductratingscount,totalurgencycount,urgencytextrate
count,958.000000,958.000000,958.000000,958.000000,9.580000e+02,958.000000,958.000000,958.000000,958.000000,958.000000,391.000000,391.000000
mean,1.641962,7124.483299,4407.605428,4.043994,2.202045e+04,8.634906,24.802265,28.721294,28.698017,922.538622,1.209719,65.572890
std,1.246183,14363.521893,9167.077812,0.222137,8.473232e+04,3.987599,30.258719,39.918708,39.914269,1925.750178,0.583542,28.476426
min,1.000000,1.000000,1.000000,2.333000,0.000000e+00,1.000000,1.000000,-18.000000,-18.000000,0.000000,1.000000,14.000000
25%,1.000000,100.000000,100.000000,3.931000,1.373000e+03,6.000000,7.000000,-10.000000,-10.000000,31.000000,1.000000,50.000000
50%,1.000000,1000.000000,1000.000000,4.055500,5.990500e+03,8.000000,11.000000,16.000000,16.000000,210.500000,1.000000,50.000000
75%,2.000000,10000.000000,5000.000000,4.190000,1.723850e+04,11.000000,28.875000,71.000000,71.000000,920.750000,1.000000,100.000000
max,15.000000,120000.000000,100000.000000,5.000000,2.174765e+06,49.000000,252.000000,97.000000,97.000000,20744.000000,6.000000,100.000000

In [ ]:
import pandas as pd

df = pd.read_csv('computed_insight_success_of_active_sellers.csv')
df.shape

(958, 13)

In [ ]:
import pandas as pd

df = pd.read_csv('computed_insight_success_of_active_sellers.csv')
df.columns

Index(['merchantid', 'listedproducts', 'totalunitssold',
       'meanunitssoldperproduct', 'rating', 'merchantratingscount',
       'meanproductprices', 'meanretailprices', 'averagediscount',
       'meandiscount', 'meanproductratingscount', 'totalurgencycount',
       'urgencytextrate'],
      dtype='object')

In [ ]:
import pandas as pd

df = pd.read_csv('computed_insight_success_of_active_sellers.csv')
df.isnull().sum()

merchantid                   0
listedproducts               0
totalunitssold               0
meanunitssoldperproduct      0
rating                       0
merchantratingscount         0
meanproductprices            0
meanretailprices             0
averagediscount              0
meandiscount                 0
meanproductratingscount      0
totalurgencycount          567
urgencytextrate            567
dtype: int64

In [ ]:
import pandas as pd

df = pd.read_csv('computed_insight_success_of_active_sellers.csv')
df.duplicated().sum()

np.int64(0)

In [ ]:
import pandas as pd

df = pd.read_csv('computed_insight_success_of_active_sellers.csv')
df = df.drop_duplicates()
print(df)

                   merchantid  listedproducts  totalunitssold  \
0    5357bcf2bb72c5504882e889               2          120000
1    5708773c3c02161b3f8c7900               5          107100
2    5417aada4ad3ab27e954b76c               2          100007
3    570f3a713a698c14278bb51e               1          100000
4    53082ea15aefb07dfe1f2a4f               1          100000
..                        ...             ...             ...
953  567bad8582c35f28103e5813               1               2
954  5b24edf0d1c360301099e9c6               1               2
955  5d417e7070327a2743021677               1               1
956  5add589edb5f1f32114d07df               1               1
957  5d4b8931933fb13f8a1fe232               1               1

     meanunitssoldperproduct  rating  merchantratingscount  meanproductprices  \
0                    60000.0   4.219              320031.0               9.00
1                    21420.0   3.934              139223.0               7.76
2                    50004.0   4.053              108048.0               8.00
3                   100000.0   3.889               19248.0               5.67
4                   100000.0   4.036              366898.0               5.00
..                       ...     ...                   ...                ...
953                      2.0   3.999               21307.0              11.00
954                      2.0   4.303                 693.0              16.00
955                      1.0   3.598                 378.0               2.72
956                      1.0   3.956                1134.0              14.00
957                      1.0   4.007                1380.0              11.00

     meanretailprices  averagediscount  meandiscount  meanproductratingscount  \
0                20.0             54.0          54.0                   8836.0
1                34.2             61.0          61.0                   4010.0
2                 8.0             -1.0          -1.0                   5531.0
3                19.0             71.0          71.0                  18393.0
4                33.0             85.0          85.0                  13789.0
..                ...              ...           ...                      ...
953              10.0            -10.0         -10.0                      1.0
954              16.0              0.0           0.0                      0.0
955               9.0             70.0          70.0                      0.0
956              14.0              0.0           0.0                      0.0
957              30.0             64.0          64.0                      0.0

     totalurgencycount  urgencytextrate
0                  1.0             50.0
1                  3.0             60.0
2                  NaN              NaN
3                  1.0            100.0
4                  NaN              NaN
..                 ...              ...
953                NaN              NaN
954                NaN              NaN
955                NaN              NaN
956                NaN              NaN
957                NaN              NaN

[958 rows x 13 columns]

In [ ]:
import pandas as pd

df = pd.read_csv('computed_insight_success_of_active_sellers.csv')
df = df.fillna(0)
print(df)

                   merchantid  listedproducts  totalunitssold  \
0    5357bcf2bb72c5504882e889               2          120000
1    5708773c3c02161b3f8c7900               5          107100
2    5417aada4ad3ab27e954b76c               2          100007
3    570f3a713a698c14278bb51e               1          100000
4    53082ea15aefb07dfe1f2a4f               1          100000
..                        ...             ...             ...
953  567bad8582c35f28103e5813               1               2
954  5b24edf0d1c360301099e9c6               1               2
955  5d417e7070327a2743021677               1               1
956  5add589edb5f1f32114d07df               1               1
957  5d4b8931933fb13f8a1fe232               1               1

     meanunitssoldperproduct  rating  merchantratingscount  meanproductprices  \
0                    60000.0   4.219              320031.0               9.00
1                    21420.0   3.934              139223.0               7.76
2                    50004.0   4.053              108048.0               8.00
3                   100000.0   3.889               19248.0               5.67
4                   100000.0   4.036              366898.0               5.00
..                       ...     ...                   ...                ...
953                      2.0   3.999               21307.0              11.00
954                      2.0   4.303                 693.0              16.00
955                      1.0   3.598                 378.0               2.72
956                      1.0   3.956                1134.0              14.00
957                      1.0   4.007                1380.0              11.00

     meanretailprices  averagediscount  meandiscount  meanproductratingscount  \
0                20.0             54.0          54.0                   8836.0
1                34.2             61.0          61.0                   4010.0
2                 8.0             -1.0          -1.0                   5531.0
3                19.0             71.0          71.0                  18393.0
4                33.0             85.0          85.0                  13789.0
..                ...              ...           ...                      ...
953              10.0            -10.0         -10.0                      1.0
954              16.0              0.0           0.0                      0.0
955               9.0             70.0          70.0                      0.0
956              14.0              0.0           0.0                      0.0
957              30.0             64.0          64.0                      0.0

     totalurgencycount  urgencytextrate
0                  1.0             50.0
1                  3.0             60.0
2                  0.0              0.0
3                  1.0            100.0
4                  0.0              0.0
..                 ...              ...
953                0.0              0.0
954                0.0              0.0
955                0.0              0.0
956                0.0              0.0
957                0.0              0.0

[958 rows x 13 columns]

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('computed_insight_success_of_active_sellers.csv')
df['estimated_revenue'] = df['totalunitssold'] * df['meanproductprices']
print(df)

                   merchantid  listedproducts  totalunitssold  \
0    5357bcf2bb72c5504882e889               2          120000
1    5708773c3c02161b3f8c7900               5          107100
2    5417aada4ad3ab27e954b76c               2          100007
3    570f3a713a698c14278bb51e               1          100000
4    53082ea15aefb07dfe1f2a4f               1          100000
..                        ...             ...             ...
953  567bad8582c35f28103e5813               1               2
954  5b24edf0d1c360301099e9c6               1               2
955  5d417e7070327a2743021677               1               1
956  5add589edb5f1f32114d07df               1               1
957  5d4b8931933fb13f8a1fe232               1               1

     meanunitssoldperproduct  rating  merchantratingscount  meanproductprices  \
0                    60000.0   4.219              320031.0               9.00
1                    21420.0   3.934              139223.0               7.76
2                    50004.0   4.053              108048.0               8.00
3                   100000.0   3.889               19248.0               5.67
4                   100000.0   4.036              366898.0               5.00
..                       ...     ...                   ...                ...
953                      2.0   3.999               21307.0              11.00
954                      2.0   4.303                 693.0              16.00
955                      1.0   3.598                 378.0               2.72
956                      1.0   3.956                1134.0              14.00
957                      1.0   4.007                1380.0              11.00

     meanretailprices  averagediscount  meandiscount  meanproductratingscount  \
0                20.0             54.0          54.0                   8836.0
1                34.2             61.0          61.0                   4010.0
2                 8.0             -1.0          -1.0                   5531.0
3                19.0             71.0          71.0                  18393.0
4                33.0             85.0          85.0                  13789.0
..                ...              ...           ...                      ...
953              10.0            -10.0         -10.0                      1.0
954              16.0              0.0           0.0                      0.0
955               9.0             70.0          70.0                      0.0
956              14.0              0.0           0.0                      0.0
957              30.0             64.0          64.0                      0.0

     totalurgencycount  urgencytextrate  estimated_revenue
0                  1.0             50.0         1080000.00
1                  3.0             60.0          831096.00
2                  NaN              NaN          800056.00
3                  1.0            100.0          567000.00
4                  NaN              NaN          500000.00
..                 ...              ...                ...
953                NaN              NaN              22.00
954                NaN              NaN              32.00
955                NaN              NaN               2.72
956                NaN              NaN              14.00
957                NaN              NaN              11.00

[958 rows x 14 columns]

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('computed_insight_success_of_active_sellers.csv')
df['price_difference'] = df['meanretailprices'] - df['meanproductprices']
print(df)

                   merchantid  listedproducts  totalunitssold  \
0    5357bcf2bb72c5504882e889               2          120000
1    5708773c3c02161b3f8c7900               5          107100
2    5417aada4ad3ab27e954b76c               2          100007
3    570f3a713a698c14278bb51e               1          100000
4    53082ea15aefb07dfe1f2a4f               1          100000
..                        ...             ...             ...
953  567bad8582c35f28103e5813               1               2
954  5b24edf0d1c360301099e9c6               1               2
955  5d417e7070327a2743021677               1               1
956  5add589edb5f1f32114d07df               1               1
957  5d4b8931933fb13f8a1fe232               1               1

     meanunitssoldperproduct  rating  merchantratingscount  meanproductprices  \
0                    60000.0   4.219              320031.0               9.00
1                    21420.0   3.934              139223.0               7.76
2                    50004.0   4.053              108048.0               8.00
3                   100000.0   3.889               19248.0               5.67
4                   100000.0   4.036              366898.0               5.00
..                       ...     ...                   ...                ...
953                      2.0   3.999               21307.0              11.00
954                      2.0   4.303                 693.0              16.00
955                      1.0   3.598                 378.0               2.72
956                      1.0   3.956                1134.0              14.00
957                      1.0   4.007                1380.0              11.00

     meanretailprices  averagediscount  meandiscount  meanproductratingscount  \
0                20.0             54.0          54.0                   8836.0
1                34.2             61.0          61.0                   4010.0
2                 8.0             -1.0          -1.0                   5531.0
3                19.0             71.0          71.0                  18393.0
4                33.0             85.0          85.0                  13789.0
..                ...              ...           ...                      ...
953              10.0            -10.0         -10.0                      1.0
954              16.0              0.0           0.0                      0.0
955               9.0             70.0          70.0                      0.0
956              14.0              0.0           0.0                      0.0
957              30.0             64.0          64.0                      0.0

     totalurgencycount  urgencytextrate  price_difference
0                  1.0             50.0             11.00
1                  3.0             60.0             26.44
2                  NaN              NaN              0.00
3                  1.0            100.0             13.33
4                  NaN              NaN             28.00
..                 ...              ...               ...
953                NaN              NaN             -1.00
954                NaN              NaN              0.00
955                NaN              NaN              6.28
956                NaN              NaN              0.00
957                NaN              NaN             19.00

[958 rows x 14 columns]

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('computed_insight_success_of_active_sellers.csv')
top_sellers = df.sort_values(by='totalunitssold', ascending=False)
top_sellers.head(10)

,merchantid,listedproducts,totalunitssold,meanunitssoldperproduct,rating,merchantratingscount,meanproductprices,meanretailprices,averagediscount,meandiscount,meanproductratingscount,totalurgencycount,urgencytextrate
0,5357bcf2bb72c5504882e889,2,120000,60000.0,4.219,320031.0,9.00,20.00,54.0,54.00,8836.0,1.0,50.0
1,5708773c3c02161b3f8c7900,5,107100,21420.0,3.934,139223.0,7.76,34.20,61.0,61.00,4010.0,3.0,60.0
2,5417aada4ad3ab27e954b76c,2,100007,50004.0,4.053,108048.0,8.00,8.00,-1.0,-1.00,5531.0,NaN,NaN
4,53082ea15aefb07dfe1f2a4f,1,100000,100000.0,4.036,366898.0,5.00,33.00,85.0,85.00,13789.0,NaN,NaN
5,53f2beb39020ee03566d6e18,1,100000,100000.0,4.067,330405.0,5.77,48.00,88.0,88.00,20744.0,NaN,NaN
3,570f3a713a698c14278bb51e,1,100000,100000.0,3.889,19248.0,5.67,19.00,71.0,71.00,18393.0,1.0,100.0
6,5926c5ace8ff5525241b368d,7,96000,13714.0,4.139,55499.0,6.69,6.29,-4.0,-3.86,2250.0,1.0,14.0
7,5860c757b1e41d4d67d183e8,4,90100,22525.0,4.049,151249.0,3.43,3.75,11.0,11.00,6290.0,2.0,50.0
9,5a7b23a69bda4e3d375e7b3f,5,80000,16000.0,3.966,12974.0,8.40,7.80,-7.0,-6.80,2093.0,1.0,20.0
8,52bd3ddb34067e4620a4c62d,3,80000,26667.0,4.104,839882.0,7.22,14.67,33.0,33.33,6136.0,1.0,33.0

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('computed_insight_success_of_active_sellers.csv')
df['rating'].value_counts()

high_rated = df[df['rating'] > 4]
high_rated[['merchantid','rating','totalunitssold']].head()

                 merchantid  rating  totalunitssold
0  5357bcf2bb72c5504882e889   4.219          120000
2  5417aada4ad3ab27e954b76c   4.053          100007
4  53082ea15aefb07dfe1f2a4f   4.036          100000
5  53f2beb39020ee03566d6e18   4.067          100000
6  5926c5ace8ff5525241b368d   4.139           96000

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('computed_insight_success_of_active_sellers.csv')
df.groupby('rating')['totalunitssold'].mean()

rating
2.333     10.0
2.941    100.0
3.000    100.0
3.034    100.0
3.039    100.0
         ...
4.501     10.0
4.513     10.0
4.522    100.0
4.578    100.0
5.000    100.0
Name: totalunitssold, Length: 552, dtype: float64

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('computed_insight_success_of_active_sellers.csv')
df.groupby('meanproductprices')['totalunitssold'].mean()

meanproductprices
1.00      383.333333
1.66     1000.000000
1.67      100.000000
1.68     1000.000000
1.72      100.000000
            ...
22.00    7333.333333
24.00    1000.000000
25.00      50.000000
27.00      50.000000
49.00     100.000000
Name: totalunitssold, Length: 193, dtype: float64

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('computed_insight_success_of_active_sellers.csv')
df.corr(numeric_only=True)

,listedproducts,totalunitssold,meanunitssoldperproduct,rating,merchantratingscount,meanproductprices,meanretailprices,averagediscount,meandiscount,meanproductratingscount,totalurgencycount,urgencytextrate
listedproducts,1.000000,0.383373,-0.009870,-0.069052,0.069665,-0.102308,-0.065981,-0.075254,-0.075709,-0.022501,0.735599,-0.663994
totalunitssold,0.383373,1.000000,0.804250,0.094833,0.296667,-0.069331,-0.007848,-0.027921,-0.027895,0.738898,0.256122,-0.277469
meanunitssoldperproduct,-0.009870,0.804250,1.000000,0.119518,0.264941,-0.066693,0.007179,0.010164,0.010276,0.918040,-0.010458,0.017087
rating,-0.069052,0.094833,0.119518,1.000000,0.119780,0.014013,0.034795,0.014893,0.014926,0.144358,-0.075987,0.154485
merchantratingscount,0.069665,0.296667,0.264941,0.119780,1.000000,-0.032802,0.013628,0.001100,0.001196,0.245683,0.071331,-0.121559
meanproductprices,-0.102308,-0.069331,-0.066693,0.014013,-0.032802,1.000000,0.292684,-0.047601,-0.047614,-0.036925,-0.118870,0.161271
meanretailprices,-0.065981,-0.007848,0.007179,0.034795,0.013628,0.292684,1.000000,0.718960,0.718903,0.059183,-0.096515,0.044781
averagediscount,-0.075254,-0.027921,0.010164,0.014893,0.001100,-0.047601,0.718960,1.000000,0.999994,0.020580,-0.060869,0.104026
meandiscount,-0.075709,-0.027895,0.010276,0.014926,0.001196,-0.047614,0.718903,0.999994,1.000000,0.020746,-0.060904,0.104704
meanproductratingscount,-0.022501,0.738898,0.918040,0.144358,0.245683,-0.036925,0.059183,0.020580,0.020746,1.000000,-0.026682,0.035119
totalurgencycount,0.735599,0.256122,-0.010458,-0.075987,0.071331,-0.118870,-0.096515,-0.060869,-0.060904,-0.026682,1.000000,-0.131618
urgencytextrate,-0.663994,-0.277469,0.017087,0.154485,-0.121559,0.161271,0.044781,0.104026,0.104704,0.035119,-0.131618,1.000000

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('computed_insight_success_of_active_sellers.csv')
successful_sellers = df[
    (df['rating'] > 4) &
    (df['totalunitssold'] > 50000)
]

successful_sellers.head()

,merchantid,listedproducts,totalunitssold,meanunitssoldperproduct,rating,merchantratingscount,meanproductprices,meanretailprices,averagediscount,meandiscount,meanproductratingscount,totalurgencycount,urgencytextrate
0,5357bcf2bb72c5504882e889,2,120000,60000.0,4.219,320031.0,9.00,20.00,54.0,54.00,8836.0,1.0,50.0
2,5417aada4ad3ab27e954b76c,2,100007,50004.0,4.053,108048.0,8.00,8.00,-1.0,-1.00,5531.0,NaN,NaN
4,53082ea15aefb07dfe1f2a4f,1,100000,100000.0,4.036,366898.0,5.00,33.00,85.0,85.00,13789.0,NaN,NaN
5,53f2beb39020ee03566d6e18,1,100000,100000.0,4.067,330405.0,5.77,48.00,88.0,88.00,20744.0,NaN,NaN
6,5926c5ace8ff5525241b368d,7,96000,13714.0,4.139,55499.0,6.69,6.29,-4.0,-3.86,2250.0,1.0,14.0

In [ ]:
df.to_csv('processed_sellers_data.csv', index=False)